name: TeXLive Action

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Github TeXLive Action
      continue-on-error: true
      uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            make

    - name: List
      run: |
        echo "::group::List env vars"
        env | sort
        echo "::endgroup::"
        echo "::group::working directory (pwd)"
        pwd
        echo "::endgroup::"
        echo "::group::Recursive list files from working directory"
        ls -lR
        echo "::endgroup::"
        echo "::group::Output thesis.log"
        if [ -e thesis.log ] ; then cat thesis.log ; fi
        echo "::endgroup::"
